<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FurinaArchive.Services\FurinaArchive.Services.csproj" />
    <ProjectReference Include="..\FurinaArchive.Core\FurinaArchive.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" Version="1.11.285" />
  </ItemGroup>

</Project>
